/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.7
 * Generated at: 2022-06-20 04:40:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.tag.web;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class dashboard_tag
    extends jakarta.servlet.jsp.tagext.SimpleTagSupport
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private jakarta.servlet.jsp.JspContext jspContext;
  private java.io.Writer _jspx_sout;
  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public void setJspContext(jakarta.servlet.jsp.JspContext ctx) {
    super.setJspContext(ctx);
    java.util.ArrayList _jspx_nested = null;
    java.util.ArrayList _jspx_at_begin = null;
    java.util.ArrayList _jspx_at_end = null;
    this.jspContext = new org.apache.jasper.runtime.JspContextWrapper(this, ctx, _jspx_nested, _jspx_at_begin, _jspx_at_end, null);
  }

  public jakarta.servlet.jsp.JspContext getJspContext() {
    return this.jspContext;
  }
  private java.lang.String message;
  private java.lang.String title;
  private jakarta.servlet.jsp.tagext.JspFragment content;

  public java.lang.String getMessage() {
    return this.message;
  }

  public void setMessage(java.lang.String message) {
    this.message = message;
    jspContext.setAttribute("message", message);
  }

  public java.lang.String getTitle() {
    return this.title;
  }

  public void setTitle(java.lang.String title) {
    this.title = title;
    jspContext.setAttribute("title", title);
  }

  public jakarta.servlet.jsp.tagext.JspFragment getContent() {
    return this.content;
  }

  public void setContent(jakarta.servlet.jsp.tagext.JspFragment content) {
    this.content = content;
    jspContext.setAttribute("content", content);
  }

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    return _jsp_instancemanager;
  }

  private void _jspInit(jakarta.servlet.ServletConfig config) {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(config.getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(config);
  }

  public void _jspDestroy() {
  }

  public void doTag() throws jakarta.servlet.jsp.JspException, java.io.IOException {
    jakarta.servlet.jsp.PageContext _jspx_page_context = (jakarta.servlet.jsp.PageContext)jspContext;
    jakarta.servlet.http.HttpServletRequest request = (jakarta.servlet.http.HttpServletRequest) _jspx_page_context.getRequest();
    jakarta.servlet.http.HttpServletResponse response = (jakarta.servlet.http.HttpServletResponse) _jspx_page_context.getResponse();
    jakarta.servlet.http.HttpSession session = _jspx_page_context.getSession();
    jakarta.servlet.ServletContext application = _jspx_page_context.getServletContext();
    jakarta.servlet.ServletConfig config = _jspx_page_context.getServletConfig();
    jakarta.servlet.jsp.JspWriter out = jspContext.getOut();
    _jspInit(config);
    jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,jspContext);
    if( getMessage() != null ) 
      _jspx_page_context.setAttribute("message", getMessage());
    if( getTitle() != null ) 
      _jspx_page_context.setAttribute("title", getTitle());
    if( getContent() != null ) 
      _jspx_page_context.setAttribute("content", getContent());

    try {
      out.write(" \n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!doctype html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"utf-8\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("        <meta name=\"description\" content=\"\">\n");
      out.write("        <meta name=\"author\" content=\"Reynaldo Mejia\">\n");
      out.write("        <meta name=\"generator\" content=\"RMR_1.0.0\">\n");
      out.write("        <title>Electronic Shop &copy;</title>\n");
      out.write("\n");
      out.write("        <link rel=\"canonical\" href=\"https://getbootstrap.com/docs/5.1/examples/dashboard/\">\n");
      out.write("        <link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("/logoEShop.png\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"//cdn.datatables.net/1.10.11/css/jquery.dataTables.css\">\n");
      out.write("        <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("/jquery-3.3.1.js\" type=\"text/javascript\"></script>\n");
      out.write("        <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("/jquery-3.3.1.min.js\" type=\"text/javascript\"></script>\n");
      out.write("        <script type=\"text/javascript\" charset=\"utf8\" src=\"//cdn.datatables.net/1.10.11/js/jquery.dataTables.js\"></script>\n");
      out.write("        <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("/site.js\" type=\"text/javascript\"></script>\n");
      out.write("        <!-- Bootstrap core CSS -->\n");
      out.write("        <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("/assets/dist/js/bootstrap.bundle.min.js\" type=\"text/javascript\"></script>\n");
      out.write("        <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("/assets/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.6.1/font/bootstrap-icons.css\"> \n");
      out.write("        <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("/Estilos_2.css\" rel=\"stylesheet\" type=\"text/css\"/>\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@11.1.9/dist/sweetalert2.all.min.js\"></script> \n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/sweetalert2@11.1.9/dist/sweetalert2.min.css\"> \n");
      out.write("        <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("/SweetAlertModal.css\" rel=\"stylesheet\" type=\"text/css\"/>\n");
      out.write("        <style>\n");
      out.write("            .bd-placeholder-img {\n");
      out.write("                font-size: 1.125rem;\n");
      out.write("                text-anchor: middle;\n");
      out.write("                -webkit-user-select: none;\n");
      out.write("                -moz-user-select: none;\n");
      out.write("                user-select: none;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            @media (min-width: 768px) {\n");
      out.write("                .bd-placeholder-img-lg {\n");
      out.write("                    font-size: 3.5rem;\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("        </style>\n");
      out.write("\n");
      out.write("\n");
      out.write("        <!-- Custom styles for this template -->\n");
      out.write("        <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("/dashboard.css\" rel=\"stylesheet\">\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("\n");
      out.write("        <header class=\"navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow\">\n");
      out.write("            <a class=\"navbar-brand col-md-3 col-lg-2 me-0 px-3\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("/Inicio\">\n");
      out.write("                <img class=\"imagen\" width=\"30\" heigth=\"30\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("/logoEShop.png\">\n");
      out.write("                Electronic Shop &copy;</a>\n");
      out.write("            <button class=\"navbar-toggler position-absolute d-md-none collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#sidebarMenu\" aria-controls=\"sidebarMenu\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("                <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("            </button>\n");
      out.write("            <input class=\"form-control form-control-dark w-100\" type=\"text\" placeholder=\"Buscar\" aria-label=\"Buscar\" style=\"display:none;\">  \n");
      out.write("            <div class=\"form-control form-control-dark w-100\" style=\"background-color:#212529 \">\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("            <div class=\"navbar-nav\">\n");
      out.write("                <div class=\"nav-item text-nowrap\">\n");
      out.write("                    <a class=\"nav-link px-3\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("/Carrito\">\n");
      out.write("                        <span class=\"bi bi-cart4\"></span>\n");
      out.write("                        Mis Compras</a>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("            <div class=\"navbar-nav\">\n");
      out.write("                <div class=\"nav-item text-nowrap\">\n");
      out.write("                    <a class=\"nav-link px-3\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("/Perfil\">\n");
      out.write("                        <i class=\"bi bi-person\"></i>\n");
      out.write("                        Perfil</a>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("            <div class=\"navbar-nav\">\n");
      out.write("                <div class=\"nav-item text-nowrap\">\n");
      out.write("                    <a class=\"nav-link px-3\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("/Direcciones\">\n");
      out.write("                        <i class=\"bi bi-geo-alt\"></i>\n");
      out.write("                        Mis direcciones</a>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"navbar-nav\">\n");
      out.write("                <div class=\"nav-item text-nowrap\"> <!--href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("/LogOut\"-->\n");
      out.write("                    <a class=\"nav-link px-3\" id=\"logOut\">\n");
      out.write("                              <!--  <img class=\"imagen\" width=\"25\" heigth=\"25\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("/logoutEShop.svg\">-->\n");
      out.write("                        <i class=\"bi bi-door-open\"></i>\n");
      out.write("                        Cerrar Sesión</a>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("        </header>\n");
      out.write("\n");
      out.write("        <div class=\"container-fluid\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <nav id=\"sidebarMenu\" class=\"col-md-3 col-lg-2 d-md-block bg-light sidebar collapse\">\n");
      out.write("                    <div class=\"position-sticky pt-3\">\n");
      out.write("                        <ul class=\"nav flex-column\">\n");
      out.write("                            <li class=\"nav-item\">\n");
      out.write("                                <a class=\"nav-link\" aria-current=\"page\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("/Inicio\">\n");
      out.write("                                    <span data-feather=\"home\" ></span>\n");
      out.write("                                    Inicio\n");
      out.write("                                </a>\n");
      out.write("                            </li>\n");
      out.write("                            <li class=\"nav-item\" >\n");
      out.write("                                <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("/Compras\">\n");
      out.write("                                    <!-- <span data-feather=\"file\"></span>-->\n");
      out.write("\n");
      out.write("                                    <i class=\"bi bi-basket\"></i>\n");
      out.write("                                    Compras\n");
      out.write("                                </a>\n");
      out.write("                            </li>\n");
      out.write("                            <li class=\"nav-item\" id=\"p\">\n");
      out.write("                                <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("/Productos\" style=\"color:red\">\n");
      out.write("                                    <!--  <span data-feather=\"shopping-cart\"></span> -->\n");
      out.write("                                    <span class=\"bi bi-layout-wtf\"></span>\n");
      out.write("                                    Productos\n");
      out.write("                                </a>\n");
      out.write("                            </li>\n");
      out.write("                            <li class=\"nav-item\" id=\"u\">\n");
      out.write("                                <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("/Usuarios\" style=\"color:red\">\n");
      out.write("                                    <span data-feather=\"users\" style=\"color:red\"></span>\n");
      out.write("                                    Usuarios\n");
      out.write("                                </a>\n");
      out.write("                            </li>\n");
      out.write("                            <li class=\"nav-item\">\n");
      out.write("                                <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("/Pedidos\">\n");
      out.write("                                    <i class=\"bi bi-receipt-cutoff\"></i>\n");
      out.write("                                    Mis pedidos\n");
      out.write("                                </a>\n");
      out.write("                            </li>\n");
      out.write("                            <li class=\"nav-item\">\n");
      out.write("                                <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("/WishList\">\n");
      out.write("                                    <i class=\"bi bi-ui-checks-grid\"></i>\n");
      out.write("                                    Lista de deseos\n");
      out.write("                                </a>\n");
      out.write("                            </li>\n");
      out.write("                        </ul>\n");
      out.write("\n");
      out.write("                                             <h6 class=\"sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted\" >\n");
      out.write("                                                 <span>Categorias</span>\n");
      out.write("                                                                      <!--   <a class=\"link-secondary\" href=\"#\" aria-label=\"Add a new report\" id=\"cat\">\n");
      out.write("                                                     <span data-feather=\"plus-circle\" style=\"color:red\"></span>\n");
      out.write("                                                 </a> -->\n");
      out.write("                                             </h6>\n");
      out.write("                                          \n");
      out.write("                                  \n");
      out.write("                       \n");
      out.write("                        <ul class=\"nav flex-column mb-2\">\n");
      out.write("                            <li class=\"nav-item\">\n");
      out.write("                                <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("/DatLaptosSource?idCP=1\">\n");
      out.write("                                    <i class=\"bi bi-laptop\"></i>\n");
      out.write("                                    Laptop\n");
      out.write("                                </a>\n");
      out.write("                            </li>\n");
      out.write("                            <li class=\"nav-item\">\n");
      out.write("                                <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("/DatTabletSource?idCP=2\">\n");
      out.write("                                    <i class=\"bi bi-tablet\"></i>\n");
      out.write("\n");
      out.write("                                    Tablet\n");
      out.write("                                </a>\n");
      out.write("                            </li>\n");
      out.write("                            <li class=\"nav-item\">\n");
      out.write("                                <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("/DatAcceSource?idCP=3\">\n");
      out.write("                                    <i class=\"bi bi-controller\"></i>\n");
      out.write("                                    Accesorios\n");
      out.write("                                </a>\n");
      out.write("                            </li>\n");
      out.write("                            <li class=\"nav-item\">\n");
      out.write("                                <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("/DatMovilesSource?idCP=4\">\n");
      out.write("                                    <i class=\"bi bi-phone\"></i>\n");
      out.write("                                    Moviles\n");
      out.write("                                </a>\n");
      out.write("                            </li>\n");
      out.write("                            <li class=\"nav-item\">\n");
      out.write("                                <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("/DatProtectoresSource?idCP=5\">\n");
      out.write("                                    <i class=\"bi bi-aspect-ratio\"></i>\n");
      out.write("                                    Protectores\n");
      out.write("                                </a>\n");
      out.write("                            </li>\n");
      out.write("                        </ul>\n");
      out.write("                    </div>\n");
      out.write("                </nav>\n");
      out.write("\n");
      out.write("                <main class=\"col-md-9 ms-sm-auto col-lg-10 px-md-4\" >\n");
      out.write("\n");
      out.write("\n");
      out.write("                    ");
      ((org.apache.jasper.runtime.JspContextWrapper) this.jspContext).syncBeforeInvoke();
      _jspx_sout = null;
      if (getContent() != null) {
        getContent().invoke(_jspx_sout);
      }
      out.write("\n");
      out.write("\n");
      out.write("                    </main>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <br>\n");
      out.write("            <br>\n");
      out.write("            <footer class=\" text-center text-white\" style=\"background-color: #f1f1f1;\">\n");
      out.write("                <!-- Grid container -->\n");
      out.write("                <div class=\"container pt-1 d-flex justify-content-center flex-wrap flex-md-nowrap align-items-center\">\n");
      out.write("                    <!-- Section: Social media -->\n");
      out.write("                    <section class=\"mb-1\">\n");
      out.write("                        <!-- Facebook -->\n");
      out.write("                        <a\n");
      out.write("                            class=\"btn btn-link btn-floating btn-lg text-dark m-1\"\n");
      out.write("                            href=\"#!\"\n");
      out.write("                            role=\"button\"\n");
      out.write("                            data-mdb-ripple-color=\"dark\"\n");
      out.write("                            ><i class=\"bi bi-facebook\"></i></a>\n");
      out.write("\n");
      out.write("                        <!-- Twitter -->\n");
      out.write("                        <a\n");
      out.write("                            class=\"btn btn-link btn-floating btn-lg text-dark m-1\"\n");
      out.write("                            href=\"#!\"\n");
      out.write("                            role=\"button\"\n");
      out.write("                            data-mdb-ripple-color=\"dark\"\n");
      out.write("                            > <i class=\"bi bi-twitter\"></i></a>\n");
      out.write("\n");
      out.write("                        <!-- Google -->\n");
      out.write("                        <a\n");
      out.write("                            class=\"btn btn-link btn-floating btn-lg text-dark m-1\"\n");
      out.write("                            href=\"#!\"\n");
      out.write("                            role=\"button\"\n");
      out.write("                            data-mdb-ripple-color=\"dark\"\n");
      out.write("                            ><i class=\"bi bi-google\"></i></a>\n");
      out.write("\n");
      out.write("                        <!-- Instagram -->\n");
      out.write("                        <a\n");
      out.write("                            class=\"btn btn-link btn-floating btn-lg text-dark m-1\"\n");
      out.write("                            href=\"#!\"\n");
      out.write("                            role=\"button\"\n");
      out.write("                            data-mdb-ripple-color=\"dark\"\n");
      out.write("                            ><i class=\"bi bi-instagram\"></i></a>\n");
      out.write("\n");
      out.write("                        <!-- Linkedin -->\n");
      out.write("                        <a\n");
      out.write("                            class=\"btn btn-link btn-floating btn-lg text-dark m-1\"\n");
      out.write("                            href=\"#!\"\n");
      out.write("                            role=\"button\"\n");
      out.write("                            data-mdb-ripple-color=\"dark\"\n");
      out.write("                            ><i class=\"bi bi-linkedin\"></i></a>\n");
      out.write("                        <!-- Github -->\n");
      out.write("                        <a\n");
      out.write("                            class=\"btn btn-link btn-floating btn-lg text-dark m-1\"\n");
      out.write("                            href=\"#!\"\n");
      out.write("                            role=\"button\"\n");
      out.write("                            data-mdb-ripple-color=\"dark\"\n");
      out.write("                            ><i class=\"fab fa-github\"></i\n");
      out.write("                            ></a>\n");
      out.write("\n");
      out.write("                        <!-- Copyright -->\n");
      out.write("\n");
      out.write("\n");
      out.write("                        <a class=\"btn btn-link btn-floating btn-lg text-dark m-1\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("/Terminos\"> Copyright 2021: Electronic Shop &copy;</a>\n");
      out.write("\n");
      out.write("                </section>\n");
      out.write("                <!-- Section: Social media -->\n");
      out.write("            </div>\n");
      out.write("            <!-- Grid container -->\n");
      out.write("\n");
      out.write("\n");
      out.write("            <!-- Copyright -->\n");
      out.write("        </footer>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("        <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("/knockout-3.5.1.debug.js\" type=\"text/javascript\"></script>\n");
      out.write("        <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("/knockout-3.5.1.js\" type=\"text/javascript\"></script>\n");
      out.write("\n");
      out.write("        <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("/assets/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js\" integrity=\"sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE\" crossorigin=\"anonymous\"></script><script src=\"https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js\" integrity=\"sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha\" crossorigin=\"anonymous\"></script>\n");
      out.write("        <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("/dashboard.js\"></script>\n");
      out.write("     <!--  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("/Compras.js\" type=\"text/javascript\"></script>-->\n");
      out.write("        <script type=\"text/javascript\">\n");
      out.write("            var path = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("\";\n");
      out.write("\n");
      out.write("            $('#logOut').on('click', function () {\n");
      out.write("\n");
      out.write("                $.ajax({\n");
      out.write("                    type: \"GET\",\n");
      out.write("                    url: path + \"/LogOut\",\n");
      out.write("                    data: {\n");
      out.write("\n");
      out.write("                    },\n");
      out.write("                    //  contentType: \"application/json; charset=utf-8\",\n");
      out.write("                    dataType: \"json\",\n");
      out.write("                    //  async: false,\n");
      out.write("                    success: function (response) {\n");
      out.write("\n");
      out.write("                        const Toast = Swal.mixin({\n");
      out.write("                            toast: true,\n");
      out.write("                            position: 'top-right',\n");
      out.write("                            iconColor: 'white',\n");
      out.write("                            customClass: {\n");
      out.write("                                popup: 'colored-toast'\n");
      out.write("                            },\n");
      out.write("                            showConfirmButton: false,\n");
      out.write("                            timer: 1000,\n");
      out.write("                            timerProgressBar: true\n");
      out.write("                        })\n");
      out.write("\n");
      out.write("                        if (response.logout == true) {\n");
      out.write("\n");
      out.write("                            Toast.fire({\n");
      out.write("                                icon: 'success',\n");
      out.write("                                title: 'Nos vemos pronto'\n");
      out.write("                            }).then((result) => {\n");
      out.write("\n");
      out.write("                                window.location.href = window.path + '/';\n");
      out.write("\n");
      out.write("                            })\n");
      out.write("                        } else {\n");
      out.write("\n");
      out.write("                            Toast.fire({\n");
      out.write("                                icon: 'error',\n");
      out.write("                                title: 'Error'\n");
      out.write("                            })\n");
      out.write("\n");
      out.write("                        }\n");
      out.write("\n");
      out.write("                    },\n");
      out.write("                    error: function (jqXHR, textStatus, errorThrown) {\n");
      out.write("                        alert(\"No llego respuesta\");\n");
      out.write("                        console.log(jqXHR);\n");
      out.write("                        console.log(errorThrown);\n");
      out.write("                    },\n");
      out.write("                });\n");
      out.write("\n");
      out.write("            });\n");
      out.write("\n");
      out.write("            $(document).ready(function () {\n");
      out.write("                console.log(\"ready!\");\n");
      out.write("                //consultar los modulos permitidos\n");
      out.write("                $.ajax({\n");
      out.write("                    type: \"GET\",\n");
      out.write("                    url: path + \"/VerificaComponentes\",\n");
      out.write("                    data: {\n");
      out.write("\n");
      out.write("                    },\n");
      out.write("                    //  contentType: \"application/json; charset=utf-8\",\n");
      out.write("                    dataType: \"json\",\n");
      out.write("                    //  async: false,\n");
      out.write("                    success: function (response) {\n");
      out.write("\n");
      out.write("                        console.log(response);\n");
      out.write("                        if (response.acceso === false) {\n");
      out.write("                            $('#p').hide();\n");
      out.write("                            $('#u').hide();\n");
      out.write("                            $('#cat').hide();\n");
      out.write("                        }\n");
      out.write("\n");
      out.write("                    },\n");
      out.write("                    error: function (jqXHR, textStatus, errorThrown) {\n");
      out.write("                        alert(\"No llego respuesta\");\n");
      out.write("                        console.log(jqXHR);\n");
      out.write("                        console.log(errorThrown);\n");
      out.write("                    },\n");
      out.write("                });\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("            });\n");
      out.write("\n");
      out.write("\n");
      out.write("        </script>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("\n");
    } catch( java.lang.Throwable t ) {
      if( t instanceof jakarta.servlet.jsp.SkipPageException )
          throw (jakarta.servlet.jsp.SkipPageException) t;
      if( t instanceof java.io.IOException )
          throw (java.io.IOException) t;
      if( t instanceof java.lang.IllegalStateException )
          throw (java.lang.IllegalStateException) t;
      if( t instanceof jakarta.servlet.jsp.JspException )
          throw (jakarta.servlet.jsp.JspException) t;
      throw new jakarta.servlet.jsp.JspException(t);
    } finally {
      jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,super.getJspContext());
      ((org.apache.jasper.runtime.JspContextWrapper) jspContext).syncEndTagFile();
    }
  }
}
