/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.7
 * Generated at: 2022-06-20 04:40:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import Logica.SessionLogic;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("Logica.SessionLogic");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(" \n");
      out.write("\n");
      out.write(" \n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>Login</title>\n");
      out.write("        <!--<link href=\"//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\" rel=\"stylesheet\" id=\"bootstrap-css\">-->\n");
      out.write("        <!--<script src=\"//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\"></script>-->\n");
      out.write("        <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.6.1/font/bootstrap-icons.css\"> \n");
      out.write("        <!--<script src=\"//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>-->\n");
      out.write("        <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/jquery-3.3.1.js\" type=\"text/javascript\"></script>\n");
      out.write("        <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/jquery-3.3.1.min.js\" type=\"text/javascript\"></script>\n");
      out.write("\n");
      out.write("        <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ModalSucess.css\" rel=\"stylesheet\" type=\"text/css\"/>\n");
      out.write("        <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/SweetAlertModal.css\" rel=\"stylesheet\" type=\"text/css\"/>\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@11.1.9/dist/sweetalert2.all.min.js\"></script> \n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/sweetalert2@11.1.9/dist/sweetalert2.min.css\"> \n");
      out.write("       <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Estilos_2.css\" rel=\"stylesheet\" type=\"text/css\"/>\n");
      out.write("\n");
      out.write("        <style>\n");
      out.write("\n");
      out.write("\n");
      out.write("            body{\n");
      out.write("                font-family: 'Mukta', sans-serif;\n");
      out.write("                height:100vh;\n");
      out.write("                min-height:550px;\n");
      out.write("                background-image: url(https://wallpapercave.com/wp/wp9442288.jpg);\n");
      out.write("                background-repeat: no-repeat;\n");
      out.write("                background-size:cover;\n");
      out.write("                background-position:center;\n");
      out.write("                position:relative;\n");
      out.write("                overflow-y: hidden;\n");
      out.write("            }\n");
      out.write("            a{\n");
      out.write("                text-decoration:none;\n");
      out.write("                color:#444444;\n");
      out.write("            }\n");
      out.write("            .login-reg-panel{\n");
      out.write("                position: relative;\n");
      out.write("                top: 50%;\n");
      out.write("                transform: translateY(-50%);\n");
      out.write("                text-align:center;\n");
      out.write("                width:80%;\n");
      out.write("                right:0;left:0;\n");
      out.write("                margin:auto;\n");
      out.write("                height:400px;\n");
      out.write("                background-color: rgba(79,115, 194, 0.9);\n");
      out.write("            }\n");
      out.write("            .white-panel{\n");
      out.write("                background-color: rgba(255,255, 255, 1);\n");
      out.write("                height:500px;\n");
      out.write("                position:absolute;\n");
      out.write("                top:-50px;\n");
      out.write("                width:50%;\n");
      out.write("                right:calc(50% - 50px);\n");
      out.write("                transition:.3s ease-in-out;\n");
      out.write("                z-index:0;\n");
      out.write("                box-shadow: 0 0 15px 9px #00000096;\n");
      out.write("            }\n");
      out.write("            .login-reg-panel input[type=\"radio\"]{\n");
      out.write("                position:relative;\n");
      out.write("                display:none;\n");
      out.write("            }\n");
      out.write("            .login-reg-panel{\n");
      out.write("                color:#FFFFFF;\n");
      out.write("            }\n");
      out.write("            .login-reg-panel #label-login, \n");
      out.write("            .login-reg-panel #label-register{\n");
      out.write("                border:1px solid #FFFFFF;\n");
      out.write("                padding:5px 5px;\n");
      out.write("                width:150px;\n");
      out.write("                display:block;\n");
      out.write("                text-align:center;\n");
      out.write("                border-radius:10px;\n");
      out.write("                cursor:pointer;\n");
      out.write("                font-weight: 600;\n");
      out.write("                font-size: 18px;\n");
      out.write("            }\n");
      out.write("            .login-info-box{\n");
      out.write("                width:30%;\n");
      out.write("                padding:0 50px;\n");
      out.write("                top:20%;\n");
      out.write("                left:0;\n");
      out.write("                position:absolute;\n");
      out.write("                text-align:left;\n");
      out.write("            }\n");
      out.write("            .register-info-box{\n");
      out.write("                width:40%;\n");
      out.write("                padding:0 50px;\n");
      out.write("                top:20%;\n");
      out.write("                right:0;\n");
      out.write("                position:absolute;\n");
      out.write("                text-align:left;\n");
      out.write("\n");
      out.write("            }\n");
      out.write("            .right-log{right:50px !important;}\n");
      out.write("\n");
      out.write("            .login-show, \n");
      out.write("            .register-show{\n");
      out.write("                z-index: 1;\n");
      out.write("                display:none;\n");
      out.write("                opacity:0;\n");
      out.write("                transition:0.3s ease-in-out;\n");
      out.write("                color:#242424;\n");
      out.write("                text-align:left;\n");
      out.write("                padding:30px;\n");
      out.write("            }\n");
      out.write("            .show-log-panel{\n");
      out.write("                display:block;\n");
      out.write("                opacity:0.9;\n");
      out.write("            }\n");
      out.write("            .login-show input[type=\"text\"], .login-show input[type=\"password\"]{\n");
      out.write("                width: 100%;\n");
      out.write("                display: block;\n");
      out.write("                margin:20px 0;\n");
      out.write("                padding: 15px;\n");
      out.write("                border: 1px solid #b5b5b5;\n");
      out.write("                outline: none;\n");
      out.write("            }\n");
      out.write("            .login-show input[type=\"button\"] {\n");
      out.write("                max-width: 150px;\n");
      out.write("                width: 100%;\n");
      out.write("                background: #444444;\n");
      out.write("                color: #f9f9f9;\n");
      out.write("                border: none;\n");
      out.write("                padding: 10px;\n");
      out.write("                text-transform: uppercase;\n");
      out.write("                border-radius: 2px;\n");
      out.write("                float:right;\n");
      out.write("                cursor:pointer;\n");
      out.write("            }\n");
      out.write("            .login-show a{\n");
      out.write("                display:inline-block;\n");
      out.write("                padding:10px 0;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .register-show input[type=\"text\"], .register-show input[type=\"password\"]{\n");
      out.write("                width: 100%;\n");
      out.write("                display: block;\n");
      out.write("                margin:15px 0;\n");
      out.write("                padding: 15px;\n");
      out.write("                border: 1px solid #b5b5b5;\n");
      out.write("                outline: none;\n");
      out.write("            }\n");
      out.write("            .register-show input[type=\"button\"] {\n");
      out.write("                max-width: 170px;\n");
      out.write("                width: 100%;\n");
      out.write("                background: #444444;\n");
      out.write("                color: #f9f9f9;\n");
      out.write("                border: none;\n");
      out.write("                padding: 10px;\n");
      out.write("                text-transform: uppercase;\n");
      out.write("                border-radius: 2px;\n");
      out.write("                float:right;\n");
      out.write("                cursor:pointer;\n");
      out.write("            }\n");
      out.write("            .credit {\n");
      out.write("                position:absolute;\n");
      out.write("                bottom:10px;\n");
      out.write("                left:10px;\n");
      out.write("                color: #3B3B25;\n");
      out.write("                margin: 0;\n");
      out.write("                padding: 0;\n");
      out.write("                font-family: Arial,sans-serif;\n");
      out.write("                text-transform: uppercase;\n");
      out.write("                font-size: 12px;\n");
      out.write("                font-weight: bold;\n");
      out.write("                letter-spacing: 1px;\n");
      out.write("                z-index: 99;\n");
      out.write("            }\n");
      out.write("            a{\n");
      out.write("                text-decoration:none;\n");
      out.write("                color:#2c7715;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("        </style>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");

    int isRed=2;
SessionLogic sl= new SessionLogic();
    sl=(SessionLogic) request.getSession().getAttribute("sessionUsuario");
        if(sl!=null){
             request.getRequestDispatcher("Inicio").forward(request, response);
           isRed=1;
     }else{
            isRed=0;
        }
     
      out.write("\n");
      out.write("      <div id=\"cover-spin\"></div>\n");
      out.write("      \n");
      out.write("        <div class=\"login-reg-panel\">\n");
      out.write("            <div class=\"login-info-box\">\n");
      out.write("                <h2>Tienes una cuenta?</h2>\n");
      out.write("                <p>Ingresa desde el siguiente enlace.</p>\n");
      out.write("                <label id=\"label-register\" for=\"log-reg-show\">Ingresar</label>\n");
      out.write("                <input type=\"radio\" name=\"active-log-panel\" id=\"log-reg-show\"  checked=\"checked\">\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"register-info-box\">\n");
      out.write("                <h2>No cuentas con una cuenta?</h2>\n");
      out.write("                <p>Registrate facilmente siguiendo el siguiente enlace.</p>\n");
      out.write("                <label id=\"label-login\" for=\"log-login-show\">Registrar</label>\n");
      out.write("                <input type=\"radio\" name=\"active-log-panel\" id=\"log-login-show\">\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"white-panel\">\n");
      out.write("                <div class=\"login-show\">\n");
      out.write("                    <h2>INGRESAR</h2>\n");
      out.write("                    <input type=\"text\" placeholder=\"Email\" data-bind=\"value:correo\">\n");
      out.write("                    <input type=\"password\" placeholder=\"Contraseña\" data-bind=\"value:pwd\">\n");
      out.write("                    <input type=\"button\"   id=\"Inicio\" value=\"INGRESAR\" data-bind=\"click:acceso\">\n");
      out.write("                  <!--  <a href=\"Vistas/error.jsp\">Recuperar Contraseña?</a>-->\n");
      out.write("                </div>\n");
      out.write("                <div class=\"register-show\">\n");
      out.write("                    <h2>REGISTRAR</h2>\n");
      out.write("                    <div class=\"row\">\n");
      out.write("                        <div class=\"col-md-4\">\n");
      out.write("                                   <input type=\"text\" placeholder=\"Nombre\" data-bind=\"value:nombre\">\n");
      out.write("                        </div>\n");
      out.write("                         <div class=\"col-md-4\">\n");
      out.write("                                 <input type=\"text\" placeholder=\"Apellido\" data-bind=\"value:ap\">\n");
      out.write("                        </div>\n");
      out.write("                         <div class=\"col-md-4\">\n");
      out.write("                                 <input type=\"text\" placeholder=\"Apellido\" data-bind=\"value:am\">\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("             \n");
      out.write("               \n");
      out.write("                    \n");
      out.write("                    <input type=\"text\" placeholder=\"Email\" data-bind=\"value:correo\">\n");
      out.write("                    <input type=\"password\" placeholder=\"Contraseña\" data-bind=\"value:pwd\">\n");
      out.write("                    <input type=\"password\" placeholder=\"Confirmar Contraseña\" data-bind=\"value:pwd2\">\n");
      out.write("                  \n");
      out.write("           <input type=\"button\"   id=\"REGISTRAR\" value=\"REGISTRAR\" data-bind=\"click:registro\">\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("    </body>\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("    <script type=\"text/javascript\">\n");
      out.write("        var path = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\n");
      out.write("        var isReload=");
      out.print(isRed);
      out.write("\n");
      out.write("        var  isObject=");
      out.print(sl);
      out.write("\n");
      out.write("        console.log(path);\n");
      out.write("        console.log(\"ISOBJECT>=>\"+isObject);\n");
      out.write("        $(document).ready(function () {\n");
      out.write("            $('.login-info-box').fadeOut();\n");
      out.write("            $('.login-show').addClass('show-log-panel');\n");
      out.write("             $('#cover-spin').hide(0);\n");
      out.write("        });\n");
      out.write("        $('.login-reg-panel input[type=\"radio\"]').on('change', function () {\n");
      out.write("            if ($('#log-login-show').is(':checked')) {\n");
      out.write("                $('.register-info-box').fadeOut();\n");
      out.write("                $('.login-info-box').fadeIn();\n");
      out.write("                $('.white-panel').addClass('right-log');\n");
      out.write("                $('.register-show').addClass('show-log-panel');\n");
      out.write("                $('.login-show').removeClass('show-log-panel');\n");
      out.write("            } else if ($('#log-reg-show').is(':checked')) {\n");
      out.write("                $('.register-info-box').fadeIn();\n");
      out.write("                $('.login-info-box').fadeOut();\n");
      out.write("                $('.white-panel').removeClass('right-log');\n");
      out.write("                $('.login-show').addClass('show-log-panel');\n");
      out.write("                $('.register-show').removeClass('show-log-panel');\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("       \n");
      out.write("      \n");
      out.write("\n");
      out.write("\n");
      out.write("    </script>\n");
      out.write("          <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Acceso.js\" type=\"text/javascript\"></script>\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/knockout-3.5.1.debug.js\" type=\"text/javascript\"></script>\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/knockout-3.5.1.js\" type=\"text/javascript\"></script>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
