/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.7
 * Generated at: 2022-06-07 22:54:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import Modelo.Usuario;
import Logica.UsuarioManager;

public final class usuarios_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("Modelo.Usuario");
    _jspx_imports_classes.add("Logica.UsuarioManager");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(" \n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write(" \n");
      out.write("        <title>Usuarios</title>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <style>\n");
      out.write("            table, th, td {\n");
      out.write("                border: 1px solid black;\n");
      out.write("            }\n");
      out.write("        </style>\n");
      out.write("        <br/>\n");
      out.write("     \n");
      out.write("        <div class=\"row col-lg-12\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("\n");
      out.write("\n");
      out.write("                ");
 String path = request.getContextPath(); 
      out.write("\n");
      out.write("     <form method=\"post\" action=\"");
      out.print( path );
      out.write("/NuevoUsuarioSet\">\n");
      out.write("               <!-- <button type=\"button\" class=\"btn btn-primary\" aria-label=\"Left Align\"\n");
      out.write("                        onclick=\"location.href = '../SimpleTestWeb/Vistas/AccionesUsuario/NuevoUsuario.jsp'\">-->\n");
      out.write("               <button type=\"submit\">\n");
      out.write("                    Nuevo\n");
      out.write("                </button>\n");
      out.write("     </form>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <br/>\n");
      out.write("        <br/>\n");
      out.write("        <div class=\"row col-lg-12\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("\n");
      out.write("                ");

     String error="";
     error=(String)request.getAttribute("error");
     if(error==null)
     error="";
                
      out.write("\n");
      out.write("                <h4 style=\"color:red\">");
      out.print(error);
      out.write("</h4>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <br/>\n");
      out.write("        <br/>\n");
      out.write("\n");
      out.write("        <div class=\"row col-lg-12\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <table class=\"table table-striped table-bordered dt-responsive nowrap\" >\n");
      out.write("\n");
      out.write("                    <thead>\n");
      out.write("                        <tr>\n");
      out.write("                            <th>Id</th>\n");
      out.write("                            <th>Nombre</th>\n");
      out.write("                            <th>Ap Paterno</th>\n");
      out.write("                            <th>Ap Materno</th>\n");
      out.write("                            <th>Correo</th>\n");
      out.write("                            <th>Opciones</th>\n");
      out.write("                        </tr>\n");
      out.write("\n");
      out.write("                    </thead>\n");
      out.write("                    <tbody\n");
      out.write("                        ");
 
              List<Usuario> usuarios=(List<Usuario>) request.getAttribute("listaUsuariosRender");
                          for(Usuario u: usuarios){
                        
      out.write("\n");
      out.write("                        <tr>\n");
      out.write("                    <td> ");
      out.print( u.getIdUsuario());
      out.write(" </td>\n");
      out.write("                    <td> ");
      out.print( u.getNombre());
      out.write(" </td>\n");
      out.write("                    <td> ");
      out.print( u.getApPaterno());
      out.write(" </td>\n");
      out.write("                    <td> ");
      out.print( u.getApMaterno());
      out.write(" </td>\n");
      out.write("                    <td> ");
      out.print( u.getCorreo());
      out.write(" </td>\n");
      out.write("                    <td>\n");
      out.write("                         <form method=\"post\" action=\"");
      out.print( path );
      out.write("/ConsultaDireccionesUsuario\">\n");
      out.write("                            <button type=\"submit\" class=\"btn btn-default\" aria-label=\"Left Align\" value=\"");
      out.print(u.getIdUsuario());
      out.write("\" name=\"usuario\" >\n");
      out.write("                                 Direcciones\n");
      out.write("                            </button>\n");
      out.write("                        </form>\n");
      out.write("                        <form method=\"post\" action=\"");
      out.print( path );
      out.write("/ConsultaUsuarioEditar\">\n");
      out.write("                            <button type=\"submit\" class=\"btn btn-default\" aria-label=\"Left Align\" value=\"");
      out.print(u.getIdUsuario());
      out.write("\" name=\"editar\">\n");
      out.write("                             Editar\n");
      out.write("                            </button>  \n");
      out.write("                        </form>    \n");
      out.write("                        <form method=\"post\" action=\"");
      out.print( path );
      out.write("/EliminarUsuario\">\n");
      out.write("                            <button type=\"submit\" class=\"btn btn-default\" aria-label=\"Left Align\" value=\"");
      out.print(u.getIdUsuario());
      out.write("\" name=\"eliminar\" >\n");
      out.write("                                 Eliminar\n");
      out.write("                            </button>\n");
      out.write("                        </form>\n");
      out.write("                    </td>\n");
      out.write("\n");
      out.write("                    ");
 
                        }
                    
      out.write("\n");
      out.write("                    </tr>\n");
      out.write("                    </tbody>\n");
      out.write("                </table>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("                  \n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
